/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Notification {
  'isRead' : boolean,
  'message' : string,
  'timestamp' : bigint,
  'notificationId' : string,
}
export interface Task {
  'deadline' : bigint,
  'taskType' : TaskType,
  'taskId' : string,
  'assignedRole' : UserRole,
  'sampleId' : string,
}
export type TaskType = { 'coa' : null } |
  { 'eligibilityCheck' : null } |
  { 'review' : null } |
  { 'analysis' : null } |
  { 'sampleIntake' : null };
export interface User {
  'principal' : Principal,
  'name' : string,
  'role' : UserRole,
  'isActive' : boolean,
}
export type UserRole = { 'qa' : null } |
  { 'admin' : null } |
  { 'sectionInCharge' : null } |
  { 'analyst' : null };
export interface _SERVICE {
  'completeTask' : ActorMethod<[string], undefined>,
  'createUser' : ActorMethod<[string, UserRole], undefined>,
  'getAllTasks' : ActorMethod<[], Array<Task>>,
  'getNotifications' : ActorMethod<[string], Array<Notification>>,
  'getSortedTasksByDeadline' : ActorMethod<[], Array<[string, Task]>>,
  'getUser' : ActorMethod<[], [] | [User]>,
  'markNotificationAsRead' : ActorMethod<[string, string], undefined>,
  'sendNotification' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];