/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'qa' : IDL.Null,
  'admin' : IDL.Null,
  'sectionInCharge' : IDL.Null,
  'analyst' : IDL.Null,
});
export const TaskType = IDL.Variant({
  'coa' : IDL.Null,
  'eligibilityCheck' : IDL.Null,
  'review' : IDL.Null,
  'analysis' : IDL.Null,
  'sampleIntake' : IDL.Null,
});
export const Task = IDL.Record({
  'deadline' : IDL.Int,
  'taskType' : TaskType,
  'taskId' : IDL.Text,
  'assignedRole' : UserRole,
  'sampleId' : IDL.Text,
});
export const Notification = IDL.Record({
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'notificationId' : IDL.Text,
});
export const User = IDL.Record({
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'role' : UserRole,
  'isActive' : IDL.Bool,
});

export const idlService = IDL.Service({
  'completeTask' : IDL.Func([IDL.Text], [], []),
  'createUser' : IDL.Func([IDL.Text, UserRole], [], []),
  'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getNotifications' : IDL.Func([IDL.Text], [IDL.Vec(Notification)], ['query']),
  'getSortedTasksByDeadline' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, Task))],
      ['query'],
    ),
  'getUser' : IDL.Func([], [IDL.Opt(User)], ['query']),
  'markNotificationAsRead' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'sendNotification' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'qa' : IDL.Null,
    'admin' : IDL.Null,
    'sectionInCharge' : IDL.Null,
    'analyst' : IDL.Null,
  });
  const TaskType = IDL.Variant({
    'coa' : IDL.Null,
    'eligibilityCheck' : IDL.Null,
    'review' : IDL.Null,
    'analysis' : IDL.Null,
    'sampleIntake' : IDL.Null,
  });
  const Task = IDL.Record({
    'deadline' : IDL.Int,
    'taskType' : TaskType,
    'taskId' : IDL.Text,
    'assignedRole' : UserRole,
    'sampleId' : IDL.Text,
  });
  const Notification = IDL.Record({
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'notificationId' : IDL.Text,
  });
  const User = IDL.Record({
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'role' : UserRole,
    'isActive' : IDL.Bool,
  });
  
  return IDL.Service({
    'completeTask' : IDL.Func([IDL.Text], [], []),
    'createUser' : IDL.Func([IDL.Text, UserRole], [], []),
    'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getNotifications' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Notification)],
        ['query'],
      ),
    'getSortedTasksByDeadline' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, Task))],
        ['query'],
      ),
    'getUser' : IDL.Func([], [IDL.Opt(User)], ['query']),
    'markNotificationAsRead' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'sendNotification' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };